name: callgraph
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.1

      - uses: actions/checkout@v2.3.4
        with:
          repository: 'protolambda/gocyto'
      - run: go get golang.org/x/tools@v0.1.0
      - run: go mod tidy
      - run: go install

      - uses: actions/checkout@v2.3.4
        with:
          repository: 'gotd/td'
      - run: go mod download
      - run: go build ./tg
      - run: curl -L -s -f -o index.gohtml https://raw.githubusercontent.com/protolambda/gocyto/master/index.gohtml
      - run: gocyto -mode cha -out out.html -web github.com/gotd/td/tg

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: callgraph
          path: out.html
